# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Iyoungman
brief-intro: Back-end Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iyoungman.github.io" # the base hostname & protocol for your site

permalink: /:categories/:title/

# other links
facebook_username: 
github_username:  iyoungman
email: 
linkedIn_username: 

description_footer: ""

# comments
disqus_shortname: iyoungman

# statistic analysis
google_analytics_id: UA-164759686-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: <!--more-->

# paginate
gems: [jekyll-paginate]
paginate: 6

# favicon
favicon: favicon.ico
